server:
  port: 52004
  servlet:
    context-path: /rws_drugbase_service
spring:
  datasource:
    url: jdbc:mysql://172.26.218.134:38965/rws?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: rws
    password: Rws#2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatabookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
ok:
  http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    max-idle-connections: 200
    keep-alive-duration: 300
swagger:
  enable: true
logging:
  config: classpath:log4j2.xml
security:
  ca: http://172.26.212.224:7002
  auth: http://172.20.210.156:8090
  type: rws
  secret:
    enabled: false
    key: 123123